[package]
name = "postman"
version = "0.1.0"
authors = ["jude-LafiteIII <judewrs@gmail.com>"]

[dependencies]
mysql = "*"
dotenv = "*"
reqwest = "*"
threadpool = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
